version: '2'

networks:
  default:

services:
  nginx:
   image: nginx:latest
   container_name: nginx
   ports:
     - "8080:80"
   volumes:
     - ./www:/usr/share/nginx/html
     - ./config/default.conf:/etc/nginx/conf.d/default.conf
   depends_on:
     - php
     - mysql
   networks:
     - default
  mysql:
   image: mysql:5.6
   container_name: mysql
   ports:
     - "3306:3306"
   volumes:
     - ./db:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=7654321
     - MYSQL_DATABASE=wordpress
     - MYSQL_USER=wordpress
     - MYSQL_PASSWORD=w0rdpr3ss
   networks:
     - default 
  php:
   build: php/
   container_name: php
   volumes:
     - ./www:/usr/share/nginx/html
   ports:
     - "9000:9000"
   networks:
     - default
